#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pv
Version  : 1.6.20
Release  : 5
URL      : http://www.ivarch.com/programs/sources/pv-1.6.20.tar.gz
Source0  : http://www.ivarch.com/programs/sources/pv-1.6.20.tar.gz
Summary  : Monitor the progress of data through a pipe
Group    : Development/Tools
License  : Artistic-2.0
Requires: pv-bin = %{version}-%{release}
Requires: pv-license = %{version}-%{release}
Requires: pv-locales = %{version}-%{release}
Requires: pv-man = %{version}-%{release}
BuildRequires : intltool-dev

%description
PV ("Pipe Viewer") is a tool for monitoring the progress of data through a
pipeline.  It can be inserted into any normal pipeline between two processes
to give a visual indication of how quickly data is passing through, how long
it has taken, how near to completion it is, and an estimate of how long it
will be until completion.

%package bin
Summary: bin components for the pv package.
Group: Binaries
Requires: pv-license = %{version}-%{release}

%description bin
bin components for the pv package.


%package license
Summary: license components for the pv package.
Group: Default

%description license
license components for the pv package.


%package locales
Summary: locales components for the pv package.
Group: Default

%description locales
locales components for the pv package.


%package man
Summary: man components for the pv package.
Group: Default

%description man
man components for the pv package.


%prep
%setup -q -n pv-1.6.20
cd %{_builddir}/pv-1.6.20

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1647059048
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1647059048
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pv
cp %{_builddir}/pv-1.6.20/doc/COPYING %{buildroot}/usr/share/package-licenses/pv/11a7758de1fddbec15253d48b4de52e96974425f
%make_install
%find_lang pv

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pv

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pv/11a7758de1fddbec15253d48b4de52e96974425f

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pv.1

%files locales -f pv.lang
%defattr(-,root,root,-)

