#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pv
Version  : 1.6.6
Release  : 3
URL      : http://ivarch.com/programs/sources/pv-1.6.6.tar.bz2
Source0  : http://ivarch.com/programs/sources/pv-1.6.6.tar.bz2
Summary  : Monitor the progress of data through a pipe
Group    : Development/Tools
License  : Artistic-2.0
Requires: pv-bin
Requires: pv-license
Requires: pv-locales
Requires: pv-man

%description
PV ("Pipe Viewer") is a tool for monitoring the progress of data through a
pipeline.  It can be inserted into any normal pipeline between two processes
to give a visual indication of how quickly data is passing through, how long
it has taken, how near to completion it is, and an estimate of how long it
will be until completion.

%package bin
Summary: bin components for the pv package.
Group: Binaries
Requires: pv-license
Requires: pv-man

%description bin
bin components for the pv package.


%package license
Summary: license components for the pv package.
Group: Default

%description license
license components for the pv package.


%package locales
Summary: locales components for the pv package.
Group: Default

%description locales
locales components for the pv package.


%package man
Summary: man components for the pv package.
Group: Default

%description man
man components for the pv package.


%prep
%setup -q -n pv-1.6.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534539248
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1534539248
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pv
cp doc/COPYING %{buildroot}/usr/share/doc/pv/doc_COPYING
%make_install
%find_lang pv

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pv

%files license
%defattr(-,root,root,-)
/usr/share/doc/pv/doc_COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/pv.1

%files locales -f pv.lang
%defattr(-,root,root,-)

